local_costmap:
  publish_voxel_map: true
  global_frame:      /tibi/odom
  robot_base_frame:  /tibi/base_footprint
  update_frequency:  1.0
  publish_frequency: 1.0
  static_map:        false
  rolling_window:    true
  obstacle_range: 4.0
  raytrace_range: 4.0
  width:     8.0
  height:    8.0
  resolution: 0.3
  transform_tolerance: 1.0
  inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 3.0
  plugins:
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
