<?xml version="1.0"?>

<root xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />
 
  <xacro:macro name="cylinder_urdf" params="HEIGHT RADIUS">

    <link name="base_footprint"/>

    <link name="base_link">
      <inertial>
        <mass value="1" />
        <origin xyz="0 0 0" />
        <inertia 
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0" 
          izz="1.0" />
       </inertial>
    </link>
    
    <joint name="base_footprint_to_base_link" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${HEIGHT/2.0}" rpy="0 0 0"/>
    </joint>
    
    <link name="body">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${HEIGHT}" radius="${RADIUS}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <cylinder length="${HEIGHT}" radius="${RADIUS}"/>
        </geometry>
        <material name="grey"/>
      </visual>
    </link>
    
    <joint name="base_link_to_body" type="fixed">
      <parent link="base_link"/>
      <child link="body"/>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </joint>
    
    <link name="top"/>
    
    <joint name="base_link_to_top" type="fixed">
      <parent link="base_link"/>
      <child link="top"/>
      <origin xyz="0 0 ${HEIGHT/2.0}" rpy="0 0 0"/>
    </joint>
    
  </xacro:macro>

</root>