#footprint: [[0.5, 0.5], [0.5, -0.5], [-0.5, -0.5], [-0.5, 0.5]]
robot_radius: 0.4

obstacle_layer:
  observation_sources: front_laser rear_laser #fake

  front_laser: {
    sensor_frame: /dabo/front_laser,
    data_type: LaserScan,
    topic: /dabo/sensors/front_laser_scan,
    observation_persistence: 0.0,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.1,
    max_obstacle_height: 2.0,
    expected_update_rate: 0
    }

  rear_laser: {
    sensor_frame: /dabo/rear_laser,
    data_type: LaserScan,
    topic: /dabo/sensors/rear_laser_scan,
    observation_persistence: 0.0,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.1,
    max_obstacle_height: 2.0,
    expected_update_rate: 0
    }

  fake_laser: {
    sensor_frame: /fake_laser,
    data_type: LaserScan,
    topic: /fake_laser,
    observation_persistence: 0.0,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.2,
    max_obstacle_height: 2.0,
    expected_update_rate: 0 
    }
