global_costmap:
  publish_voxel_map: true
  global_frame:      /map
  robot_base_frame:  /tibi/base_footprint
  update_frequency:  0.2
  publish_frequency: 0.2
  static_map:        true
  rolling_window:    false
  transform_tolerance: 1.0
  inflation_layer:
    inflation_radius: 2.0
    cost_scaling_factor: 1.5
  plugins:
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
