AkpLocalPlanner:
  move_base: False
  plan_mode: 2
  distance_mode: 1
  global_mode: 3
  vis_mode:    2
  frozen_mode: False
  number_vertex: 800
  horizon_time: 6.0
  cost_distance:    0.7
  cost_orientation: 0.5
  cost_w_robot:     0.4
  cost_w_people:    0.2
  cost_time:        0.25
  cost_obs:         0.2
  cost_old_path:    0.4
  cost_l_minima:    0.0
  v_max:  0.9
  w_max:  1.0
  av_max: 0.4
  av_break: 2.0
  aw_max: 0.9
  platform_radii: 0.5
  xy_goal_tolerance: 0.3
  distance_to_stop: 1.0
  v_goal_tolerance: 0.1
  esfm_to_person_A: 5.05
  esfm_to_person_B: 0.91
  esfm_to_person_lambda: 0.25
  esfm_to_robot_A: 4.05
  esfm_to_robot_B: 0.81
  esfm_to_robot_lambda: 0.05
  esfm_to_obstacle_A: 1.0
  esfm_to_obstacle_B: 0.2
  esfm_to_obstacle_lambda: 1.0
  esfm_k: 2.3
  esfm_d: 0.2
  min_v_to_predict : 0.1
  ppl_collision_mode : 0
  pr_force_mode : 0
  goal_providing_mode : 1
  slicing_diff_orientation : 50.0
##from launch file
#  force_map_path: "/home/fherrero/iri-lab/ros/iri-ros-pkg/iri_navigation/iri_people_simulation/map/force_map.txt"
#  destination_map_path: "/home/fherrero/iri-lab/ros/iri-ros-pkg/iri_navigation/iri_people_simulation/map/2_destinations.txt"
#  robot: "tibi"
